# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 062ee986e1ff89108d3ccd5c74ea2d055c70638d80bbf4561414f0d1419be8d2e5f213339d7eb9f53239935cb528f3fa28d57615ecd7f9fe0c1f708ee28cb0ba

test:
  secret_key_base: e8f004e2cae91537bfe2c32988a5f9800c45cfd83e19c0c1ed1e88fad6d42a5a4cc0882be49ccfa7dd96380c55871a3005803a5c3317d4d79fdf8480485ee663

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
